### ISSUE TITLE
Get started guide 

### ISSUE THREAD

**Issue by mtuchi** [thepacer/pacer-archives-symfony#114]
Hello my name is Emmanuel Evance i work at a startup called irabu (at github is [irabudev](https://github.com/irabudev)).

Currently am working to create a website where people can browse old newspaper and i think 
i can use this project as a backbone for my website application.

Kindly assist me with a proper how to get started guide. So far am stack understanding the user management side of the applicatin if there is any for people responsible for uploading the archives, I have manage to spin up the repo in my local machine but i have 0 archives so it's kinda difficult understanding how the entire application works. I want to atleast create an archive and move on from there

Assistance of any kind will be kindly appriciated
Cheers!

**Comment by stephenyeargin** [comment]
I created a guide (linked below), but I'll warn you that this is rather specialized. It serves as a "viewer" website for content already archived or Archive.org (see https://archive.org/details/thepacer/) rather than a way to manage the information directly. It might not work for your intended purpose. It does not have an administration area per se for adding new content. The lone login page is to password protect our `staging` site.

https://github.com/thepacer/pacer-archives-symfony/wiki

**Comment by mtuchi** [comment]
> I created a guide (linked below), but I'll warn you that this is rather specialized. It serves as a "viewer" website (https://www.thepacer.org) for content already archived content on Archive.org (see https://archive.org/details/thepacer/) rather than a way to manage the information directly. It might not work for your intended purpose. It does not have an administration area per se for adding new content. The lone login page is to password protect our `staging` site.
> 
> https://github.com/thepacer/pacer-archives-symfony/wiki

@stephenyeargin thank you for the guidance, atleast now i know where to begin.
